### ISSUE TITLE
Visual Bug

### ISSUE THREAD

**Issue by Kolyn090** [GeorgeZhang744/AI_Chat_Support#1]
Hello, George. First of all, this is a nice chatting app done with ChatGPT. Secondly, I want to let you know that the input text color is the same as the background (so the text is invisible) on my end. I have tried Brave, Chrome, Safari and all got the same result. I hope this can help you. Happy coding! 🔅

**Comment by GeorgeZhang744** [comment]
Hi, thank you for bringing this issue to my attention! I appreciate you testing it on multiple browsers. The input text looks fine on my end, so I'll investigate further to see what might be causing the problem. In the meantime, could you please check if any browser extensions or custom settings might be affecting the appearance? That might help narrow down the issue. Thank you.

**Comment by Kolyn090** [comment]
I believe the issue is due to you forgot to add text color in input. In its className prop, try adding "text-red-500" to see if it changes the input text color to red.

**Comment by GeorgeZhang744** [comment]
After investigating, it appears that the issue was occurring on Mac devices where the default text color was set to white instead of black. I've now addressed the problem, and it should be resolved. Thank you for bringing this to my attention.
